# Generated by Django 5.2.6 on 2025-11-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0008_tagpost_women_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='tag',
            new_name='tags',
        ),
    ]
